package main.java.UI.MainFace;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import main.java.Entity.Admin;
import main.java.Entity.Database;
import main.java.Entity.Operation;
import main.java.Entity.User;
import main.java.Interact.AddNewAccount;
import main.java.Interact.AddNewCar;
import main.java.Interact.ChangePassword;
import main.java.Interact.DeleteCar;
import main.java.UI.Control.AddNewAdminGUI;
import main.java.UI.Control.DeleteCarGUI;
import main.java.UI.Control.AddNewCarGUI;
import main.java.UI.Control.DeleteUserGUI;
import main.java.UI.Control.UpdateCarGUI;
import main.java.Interact.DeleteCar;
import main.java.Interact.DeleteUser;
import main.java.Interact.Quit;
import main.java.Interact.ShowUserBuys;
import main.java.Interact.UpdateCar;
import main.java.Interact.ViewAllUser;
import main.java.Interact.ViewCar;
import main.java.UI.Control.ChangePasswordGUI;

/**
 *
 * @author admin
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */

    public AdminDashboard() {
        initComponents();
        loadCarData(); // Tải dữ liệu khi khởi tạo giao diện
        loadUserData();
    }

    class jPanelGradient extends JPanel {

        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            Color color1 = new Color(100, 57, 255);
            Color color2 = new Color(124, 245, 255);
            int width = getWidth();
            int height = getHeight();
            GradientPaint gradientPaint = new GradientPaint(0, 0, color1, 0, height, color2);
            g2d.setPaint(gradientPaint);
            g2d.fillRect(0, 0, width, height);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bigContainer = new jPanelGradient();
        sideBar = new javax.swing.JPanel();
        sideBarLogo = new javax.swing.JLabel();
        menuSideBarPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        carLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        card = new javax.swing.JPanel();
        CarAdminPanel = new jPanelGradient();
        mainContentPanel = new jPanelGradient();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewCarTable = new javax.swing.JTable();
        addNewCarButton = new javax.swing.JButton();
        updateCarButton = new javax.swing.JButton();
        deleteCarButton = new javax.swing.JButton();
        UserAdminPanel = new jPanelGradient();
        mainContentPanel1 = new jPanelGradient();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewUserTable = new javax.swing.JTable();
        addNewAdminButton = new javax.swing.JButton();
        ShowUserBuyButton = new javax.swing.JButton();
        DeleteUserButton = new javax.swing.JButton();
        PassAdminPanel = new jPanelGradient();
        jPanel8 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPasswordField5 = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jPasswordField6 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wheel Finder Admin");
        setPreferredSize(new java.awt.Dimension(1120, 700));
        setResizable(false);

        sideBar.setBackground(new java.awt.Color(54, 171, 239));
        sideBar.setAlignmentX(0.0F);
        sideBar.setAlignmentY(0.0F);

        sideBarLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/UI/logo/logoandtext100.png"))); // NOI18N

        menuSideBarPanel.setBackground(new java.awt.Color(54, 171, 239));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/UI/logo/2logo40.png"))); // NOI18N

        carLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        carLabel.setForeground(new java.awt.Color(255, 255, 255));
        carLabel.setText("Car");
        carLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carLabelMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/UI/logo/userLogo30.png"))); // NOI18N

        userLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userLabel.setForeground(new java.awt.Color(255, 255, 255));
        userLabel.setText("User");
        userLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userLabelMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/UI/logo/changepassLogo30.png"))); // NOI18N

        passwordLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Password");
        passwordLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordLabelMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/java/UI/logo/logoutLogo35.png"))); // NOI18N

        logoutLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoutLabel.setText("Log Out");
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuSideBarPanelLayout = new javax.swing.GroupLayout(menuSideBarPanel);
        menuSideBarPanel.setLayout(menuSideBarPanelLayout);
        menuSideBarPanelLayout.setHorizontalGroup(
            menuSideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuSideBarPanelLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addGroup(menuSideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuSideBarPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(carLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(menuSideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(menuSideBarPanelLayout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(userLabel)
                            .addGap(30, 30, 30))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuSideBarPanelLayout.createSequentialGroup()
                            .addGroup(menuSideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(menuSideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(logoutLabel)
                                .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(6, 6, 6))
        );
        menuSideBarPanelLayout.setVerticalGroup(
            menuSideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuSideBarPanelLayout.createSequentialGroup()
                .addGroup(menuSideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuSideBarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(carLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuSideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuSideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuSideBarPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuSideBarPanelLayout.createSequentialGroup()
                        .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("nocopyright @ CLC04");

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuSideBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(sideBarLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sideBarLogo)
                .addGap(18, 18, 18)
                .addComponent(menuSideBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        card.setBackground(new java.awt.Color(255, 255, 255));
        card.setLayout(new java.awt.CardLayout());

        CarAdminPanel.setBackground(new java.awt.Color(255, 255, 255));

        mainContentPanel.setBackground(new java.awt.Color(255, 255, 255));

        viewCarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {}, // Không cần thêm dữ liệu mặc định tại đây
            new String [] {
                "ID", "Brand", "Model", "Color", "YearRelease", "Price", "Available"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        // Gọi hàm để tải dữ liệu
        loadCarData();
        jScrollPane1.setViewportView(viewCarTable);

        javax.swing.GroupLayout mainContentPanelLayout = new javax.swing.GroupLayout(mainContentPanel);
        mainContentPanel.setLayout(mainContentPanelLayout);
        mainContentPanelLayout.setHorizontalGroup(
            mainContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainContentPanelLayout.setVerticalGroup(
            mainContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
        );

        addNewCarButton.setBackground(new java.awt.Color(54, 171, 239));
        addNewCarButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addNewCarButton.setForeground(new java.awt.Color(255, 255, 255));
        addNewCarButton.setText("Add New Car");
        addNewCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewCarButtonActionPerformed(evt);
            }
        });

        updateCarButton.setBackground(new java.awt.Color(54, 171, 239));
        updateCarButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        updateCarButton.setForeground(new java.awt.Color(255, 255, 255));
        updateCarButton.setText("Update Car");
        updateCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCarButtonActionPerformed(evt);
            }
        });

        deleteCarButton.setBackground(new java.awt.Color(54, 171, 239));
        deleteCarButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        deleteCarButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteCarButton.setText("Delete Car");
        deleteCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CarAdminPanelLayout = new javax.swing.GroupLayout(CarAdminPanel);
        CarAdminPanel.setLayout(CarAdminPanelLayout);
        CarAdminPanelLayout.setHorizontalGroup(
            CarAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(CarAdminPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addNewCarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateCarButton)
                .addGap(12, 12, 12)
                .addComponent(deleteCarButton)
                .addGap(62, 62, 62))
        );
        CarAdminPanelLayout.setVerticalGroup(
            CarAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CarAdminPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(CarAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteCarButton)
                    .addComponent(updateCarButton)
                    .addComponent(addNewCarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        card.add(CarAdminPanel, "CarAdmin");

        UserAdminPanel.setBackground(new java.awt.Color(255, 255, 255));

        mainContentPanel1.setBackground(new java.awt.Color(255, 255, 255));

        viewUserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {}, // Không cần thêm dữ liệu mặc định tại đây
            new String [] {
                "ID", "FirstName", "LastName", "Email", "PhoneNum"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        // Gọi hàm để tải dữ liệu
        loadUserData(

        );
        jScrollPane2.setViewportView(viewUserTable);

        javax.swing.GroupLayout mainContentPanel1Layout = new javax.swing.GroupLayout(mainContentPanel1);
        mainContentPanel1.setLayout(mainContentPanel1Layout);
        mainContentPanel1Layout.setHorizontalGroup(
            mainContentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContentPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainContentPanel1Layout.setVerticalGroup(
            mainContentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
        );

        addNewAdminButton.setBackground(new java.awt.Color(54, 171, 239));
        addNewAdminButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addNewAdminButton.setForeground(new java.awt.Color(255, 255, 255));
        addNewAdminButton.setText("Add New Admin");
        addNewAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewAdminButtonActionPerformed(evt);
            }
        });

        ShowUserBuyButton.setBackground(new java.awt.Color(54, 171, 239));
        ShowUserBuyButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ShowUserBuyButton.setForeground(new java.awt.Color(255, 255, 255));
        ShowUserBuyButton.setText("Show User's Buy");
        ShowUserBuyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowUserBuyButtonActionPerformed(evt);
            }
        });

        DeleteUserButton.setBackground(new java.awt.Color(54, 171, 239));
        DeleteUserButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DeleteUserButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteUserButton.setText("Delete User");
        DeleteUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UserAdminPanelLayout = new javax.swing.GroupLayout(UserAdminPanel);
        UserAdminPanel.setLayout(UserAdminPanelLayout);
        UserAdminPanelLayout.setHorizontalGroup(
            UserAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContentPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(UserAdminPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addNewAdminButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ShowUserBuyButton)
                .addGap(12, 12, 12)
                .addComponent(DeleteUserButton)
                .addGap(62, 62, 62))
        );
        UserAdminPanelLayout.setVerticalGroup(
            UserAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserAdminPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(UserAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteUserButton)
                    .addComponent(ShowUserBuyButton)
                    .addComponent(addNewAdminButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainContentPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        card.add(UserAdminPanel, "UserAdmin");

        PassAdminPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(54, 171, 239));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("CHANGE PASSWORD");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setText("Old Password");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setText("New Password");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(54, 171, 239));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Change Password");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setText("Retype New Password");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel26))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel30)
                            .addComponent(jLabel27)
                            .addComponent(jTextField5)
                            .addComponent(jLabel28)
                            .addComponent(jPasswordField5)
                            .addComponent(jPasswordField6, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(403, 403, 403)
                        .addComponent(jButton4)))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel26)
                .addGap(86, 86, 86)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PassAdminPanelLayout = new javax.swing.GroupLayout(PassAdminPanel);
        PassAdminPanel.setLayout(PassAdminPanelLayout);
        PassAdminPanelLayout.setHorizontalGroup(
            PassAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PassAdminPanelLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PassAdminPanelLayout.setVerticalGroup(
            PassAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        card.add(PassAdminPanel, "PassAdmin");

        javax.swing.GroupLayout bigContainerLayout = new javax.swing.GroupLayout(bigContainer);
        bigContainer.setLayout(bigContainerLayout);
        bigContainerLayout.setHorizontalGroup(
            bigContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bigContainerLayout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(card, javax.swing.GroupLayout.PREFERRED_SIZE, 971, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bigContainerLayout.setVerticalGroup(
            bigContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(card, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bigContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bigContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1134, 707));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCarButtonActionPerformed
        // TODO add your handling code here:
        UpdateCarGUI updatecar = new UpdateCarGUI();
        updatecar.setVisible(true);
    }//GEN-LAST:event_updateCarButtonActionPerformed

    private void ShowUserBuyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowUserBuyButtonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ShowUserBuyButtonActionPerformed

    private void carLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carLabelMouseClicked
        // TODO add your handling code here:
        CarAdminPanel.setVisible(true);
        UserAdminPanel.setVisible(false);
        PassAdminPanel.setVisible(false);

    }//GEN-LAST:event_carLabelMouseClicked

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void userLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userLabelMouseClicked
        // TODO add your handling code here:
        CarAdminPanel.setVisible(false);
        UserAdminPanel.setVisible(true);
        PassAdminPanel.setVisible(false);
    }//GEN-LAST:event_userLabelMouseClicked

    private void passwordLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordLabelMouseClicked
        // TODO add your handling code here:
        ChangePasswordGUI changepass = new ChangePasswordGUI();
        changepass.setVisible(true);
        dispose();
    }//GEN-LAST:event_passwordLabelMouseClicked

    private void addNewCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewCarButtonActionPerformed

        AddNewCarGUI addcar = new AddNewCarGUI(this);
        addcar.setVisible(true);


    }//GEN-LAST:event_addNewCarButtonActionPerformed

    private void addNewAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewAdminButtonActionPerformed
        // TODO add your handling code here:
        AddNewAdminGUI adaddmin = new AddNewAdminGUI(this);
        adaddmin.setVisible(true);
    }//GEN-LAST:event_addNewAdminButtonActionPerformed

    private void deleteCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCarButtonActionPerformed
        DeleteCarGUI delcar = new DeleteCarGUI(this);
        delcar.setVisible(true);

    }//GEN-LAST:event_deleteCarButtonActionPerformed

    private void DeleteUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteUserButtonActionPerformed
        DeleteUserGUI delsuer = new DeleteUserGUI(this);
        delsuer.setVisible(true);
        
    }//GEN-LAST:event_DeleteUserButtonActionPerformed

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        JOptionPane.showMessageDialog(this, "Cảm ơn bạn đã dùng ứng dụng của chúng tôi", "GoodBye!!!", JOptionPane.INFORMATION_MESSAGE);
        dispose();
        StartWindow start = new StartWindow();
        start.setVisible(true);
        
    }//GEN-LAST:event_logoutLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    public void loadCarData() {
        try (Database db = new Database()) { // Sử dụng try-with-resources để tự động đóng kết nối
            Connection conn = db.getConnection(); // Lấy kết nối từ class Database
            if (conn == null) {
                System.out.println("Không thể kết nối đến cơ sở dữ liệu!");
                return;
            }

            String query = "SELECT id, brand, model, color, yearRelease, price, available FROM car";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            // Lấy mô hình bảng và xóa dữ liệu cũ
            DefaultTableModel tableModel = (DefaultTableModel) viewCarTable.getModel();
            tableModel.setRowCount(0);

            // Thêm dữ liệu mới vào bảng
            while (rs.next()) {
                Object[] row = new Object[7];
                row[0] = rs.getInt("id");
                row[1] = rs.getString("brand");
                row[2] = rs.getString("model");
                row[3] = rs.getString("color");
                row[4] = rs.getInt("yearRelease"); // Chỉnh sửa lại tên cột chính xác
                row[5] = rs.getDouble("price");
                row[6] = rs.getInt("available");
                tableModel.addRow(row);
            }

            rs.close();
            stmt.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void loadUserData() {
        try (Database db = new Database()) { // Sử dụng try-with-resources để tự động đóng kết nối
            Connection conn = db.getConnection(); // Lấy kết nối từ class Database
            if (conn == null) {
                System.out.println("Không thể kết nối đến cơ sở dữ liệu!");
                return;
            }

            String query = "SELECT id, firstName, lastName, email, phoneNum FROM user"; // Truy vấn để lấy dữ liệu người dùng
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            // Lấy mô hình bảng và xóa dữ liaệu cũ
            DefaultTableModel tableModel = (DefaultTableModel) viewUserTable.getModel();
            tableModel.setRowCount(0);

            // Thêm dữ liệu mới vào bảng
            while (rs.next()) {
                Object[] row = new Object[5]; // Cột tương ứng với 7 trường trong bảng người dùng
                row[0] = rs.getInt("id");
                row[1] = rs.getString("firstName");
                row[2] = rs.getString("lastName");
                row[3] = rs.getString("email");
                row[4] = rs.getString("phoneNum");
                tableModel.addRow(row);
            }

            rs.close();
            stmt.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CarAdminPanel;
    private javax.swing.JButton DeleteUserButton;
    private javax.swing.JPanel PassAdminPanel;
    private javax.swing.JButton ShowUserBuyButton;
    private javax.swing.JPanel UserAdminPanel;
    private javax.swing.JButton addNewAdminButton;
    private javax.swing.JButton addNewCarButton;
    private javax.swing.JPanel bigContainer;
    private javax.swing.JLabel carLabel;
    private javax.swing.JPanel card;
    private javax.swing.JButton deleteCarButton;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPasswordField jPasswordField5;
    private javax.swing.JPasswordField jPasswordField6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JPanel mainContentPanel1;
    private javax.swing.JPanel menuSideBarPanel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel sideBar;
    private javax.swing.JLabel sideBarLogo;
    private javax.swing.JButton updateCarButton;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTable viewCarTable;
    private javax.swing.JTable viewUserTable;
    // End of variables declaration//GEN-END:variables

}
