/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.UI.Control;

import javax.swing.JOptionPane; // Để hiển thị thông báo
import java.sql.Connection; // Để làm việc với kết nối cơ sở dữ liệu
import java.sql.PreparedStatement; // Để thực thi câu lệnh SQL với tham số
import java.sql.SQLException; // Để xử lý lỗi liên quan đến SQL
import main.java.Entity.Database;
import main.java.UI.MainFace.AdminDashboard;

/**
 *
 * @author admin
 */
public class AddNewAdminGUI extends javax.swing.JFrame {

    /**
     * Creates new form AddNewAdminGUI
     */
    private AdminDashboard adminboard;
    public AddNewAdminGUI(AdminDashboard adminboard) {
        this.adminboard = adminboard;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        phoneNumAddNewAdminTextField = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        passAddNewAdminTextField = new javax.swing.JPasswordField();
        retypePassAddNewAdminTextField = new javax.swing.JPasswordField();
        emailAddNewAdminTextField = new javax.swing.JTextField();
        lastNameAddNewAdminTextField = new javax.swing.JTextField();
        firstNameAddNewAdminTextField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        aNewAdminButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add New Admin");
        setMinimumSize(new java.awt.Dimension(640, 400));
        setPreferredSize(new java.awt.Dimension(640, 400));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(54, 171, 239));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Add New Admin");

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel35.setText("First Name");

        phoneNumAddNewAdminTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumAddNewAdminTextFieldActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel34.setText("Last Name");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setText("Email");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setText("Phone Number");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setText("Password");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setText("Retype Password");

        passAddNewAdminTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passAddNewAdminTextFieldActionPerformed(evt);
            }
        });

        emailAddNewAdminTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailAddNewAdminTextFieldActionPerformed(evt);
            }
        });

        lastNameAddNewAdminTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameAddNewAdminTextFieldActionPerformed(evt);
            }
        });

        firstNameAddNewAdminTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameAddNewAdminTextFieldActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(54, 171, 239));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        aNewAdminButton.setBackground(new java.awt.Color(54, 171, 239));
        aNewAdminButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aNewAdminButton.setForeground(new java.awt.Color(255, 255, 255));
        aNewAdminButton.setText("Add");
        aNewAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aNewAdminButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cancelButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                                .addComponent(aNewAdminButton))
                            .addComponent(passAddNewAdminTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(retypePassAddNewAdminTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneNumAddNewAdminTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailAddNewAdminTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameAddNewAdminTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameAddNewAdminTextField, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(firstNameAddNewAdminTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(lastNameAddNewAdminTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(emailAddNewAdminTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(phoneNumAddNewAdminTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(passAddNewAdminTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(retypePassAddNewAdminTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(aNewAdminButton))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(654, 407));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void phoneNumAddNewAdminTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumAddNewAdminTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumAddNewAdminTextFieldActionPerformed

    private void passAddNewAdminTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passAddNewAdminTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passAddNewAdminTextFieldActionPerformed

    private void emailAddNewAdminTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailAddNewAdminTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailAddNewAdminTextFieldActionPerformed

    private void lastNameAddNewAdminTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameAddNewAdminTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameAddNewAdminTextFieldActionPerformed

    private void firstNameAddNewAdminTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameAddNewAdminTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameAddNewAdminTextFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        adminboard.dispose();
    
    AdminDashboard adminboard = new AdminDashboard();
    adminboard.setVisible(true);
    dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void aNewAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aNewAdminButtonActionPerformed
        // TODO add your handling code here:
        String firstName = firstNameAddNewAdminTextField.getText();
    String lastName = lastNameAddNewAdminTextField.getText();
    String email = emailAddNewAdminTextField.getText();
    String phone = phoneNumAddNewAdminTextField.getText();
    String password = passAddNewAdminTextField.getText();
    String repass = retypePassAddNewAdminTextField.getText();
    
    // Kiểm tra xem các trường có bị bỏ trống không
    if (firstName.isEmpty() || lastName.isEmpty() || email.isEmpty() || phone.isEmpty() || password.isEmpty() || repass.isEmpty()) {
        // Hiển thị thông báo yêu cầu điền đầy đủ thông tin
        JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        return;  // Dừng lại, không tiếp tục thực hiện hành động thêm dữ liệu vào cơ sở dữ liệu
    }
    
    // Kiểm tra xem mật khẩu và xác nhận mật khẩu có khớp không
    if (!password.equals(repass)) {
        JOptionPane.showMessageDialog(this, "Mật khẩu không khớp!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        return;  // Dừng lại nếu mật khẩu không khớp
    }
    
    // Kết nối cơ sở dữ liệu và chèn dữ liệu
    try {
        // Kết nối cơ sở dữ liệu
        Database db = new Database();
        Connection conn = db.getConnection();
        
        // Câu lệnh SQL chèn dữ liệu vào bảng user
        String sql = "INSERT INTO user (firstName, lastName, email, phoneNum, passwrd, typeNum) VALUES (?, ?, ?, ?, ?, ?)";
        PreparedStatement stmt = conn.prepareStatement(sql);
        
        // Thiết lập các tham số trong câu lệnh SQL
        stmt.setString(1, firstName);
        stmt.setString(2, lastName);
        stmt.setString(3, email);
        stmt.setString(4, phone);
        stmt.setString(5, password);
        stmt.setInt(6, 1);  // Đặt typeNum là 1 (loại admin)
        
        // Thực thi câu lệnh SQL
        stmt.executeUpdate();
        
        // Đóng kết nối
        stmt.close();
        conn.close();
        
        // Hiển thị thông báo thành công
        JOptionPane.showMessageDialog(this, "Đã thêm quản admin mới thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    } catch (SQLException ex) {
        // Xử lý lỗi kết nối cơ sở dữ liệu
        JOptionPane.showMessageDialog(this, "Có lỗi khi thêm quản trị viên: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    adminboard.dispose();
    
    AdminDashboard adminboard = new AdminDashboard();
    adminboard.setVisible(true);
    dispose();
            
        


    }//GEN-LAST:event_aNewAdminButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aNewAdminButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField emailAddNewAdminTextField;
    private javax.swing.JTextField firstNameAddNewAdminTextField;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastNameAddNewAdminTextField;
    private javax.swing.JPasswordField passAddNewAdminTextField;
    private javax.swing.JTextField phoneNumAddNewAdminTextField;
    private javax.swing.JPasswordField retypePassAddNewAdminTextField;
    // End of variables declaration//GEN-END:variables
}
